name: musify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  just_audio: ^0.10.3
  just_audio_background: ^0.0.1-beta.17
  awesome_notifications: ^0.10.1
  audio_service: ^0.18.18

  device_info_plus: ^11.1.0

  flex_color_scheme: ^8.2.0

  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.8.0

  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  audiotags: ^1.4.5
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/res_play.png
    - assets/icons/res_pause.png
    - assets/icons/res_skip_next.png
    - assets/icons/res_skip_previous.png
