name: musify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  audio_session: ^0.1.21
  audiotags: ^1.4.5
  content_resolver: ^0.3.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  fftea: ^1.5.0+1
  file_picker: ^10.1.9
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_audio_capture: ^1.1.11
  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  image: ^4.5.4
  just_audio: ^0.10.3
  just_audio_background: ^0.0.1-beta.17
  marquee: ^2.3.0
  media_store_plus: ^0.1.3
  mp3_info: ^0.2.1

  once: ^1.7.0
  path: ^1.9.1
  path_provider: ^2.1.5

  permission_handler: ^12.0.0+1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
